<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Shopping</name>
   <tag></tag>
   <elementGuidId>3f434f78-e82a-4096-8bc6-643141d905ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bqHHPb']/div/div/div/a/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.FMKtTb.UqcIvb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2cad9766-1015-4e2f-9b32-f5c490c09bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FMKtTb UqcIvb</value>
      <webElementGuid>4a4681da-9036-42db-83e0-186191a26baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>pIvPIe</value>
      <webElementGuid>fcccd98c-0eaf-4213-849d-b4382cd4c837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shopping</value>
      <webElementGuid>03358f5d-9525-4443-8716-73ee6bdad6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bqHHPb&quot;)/div[@class=&quot;fMHynf Jb8vdb&quot;]/div[1]/div[@class=&quot;IUOThf&quot;]/a[@class=&quot;LatpMc nPDzT T3FoJb&quot;]/div[@class=&quot;GKS7s&quot;]/span[@class=&quot;FMKtTb UqcIvb&quot;]</value>
      <webElementGuid>095654af-8f1a-4c65-be83-192ffb71314c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bqHHPb']/div/div/div/a/div/span</value>
      <webElementGuid>b70d1e3f-4a9f-4597-96a5-e3ff4376f798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/span</value>
      <webElementGuid>35fa660b-8135-4a0d-a1ef-6d8dd6bd1ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Shopping' or . = 'Shopping')]</value>
      <webElementGuid>e930a9cd-9863-4ffa-97b7-601e68cf811d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
