<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Shop shop for dogs</name>
   <tag></tag>
   <elementGuidId>812104f9-0be0-44c4-9ac5-d77032b47582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rso']/div/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.VEbNnc.UGAWQe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>cc4895f8-2c82-4ba8-a57b-80de1fe49c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VEbNnc UGAWQe</value>
      <webElementGuid>f6ac32f0-d310-4604-bf5d-3f6dfa6c2cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop shop for dogs</value>
      <webElementGuid>eea55d60-8d6a-4a69-9ae6-a72b984f195d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rso&quot;)/div[@class=&quot;sh-sr__shop-result-group&quot;]/div[@class=&quot;R7ZAs cNSxrc CmE3ie&quot;]/h2[@class=&quot;VEbNnc UGAWQe&quot;]</value>
      <webElementGuid>521940c0-85c1-44b4-8c4c-be2a5b8ddf99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rso']/div/div/h2</value>
      <webElementGuid>8d4b9873-c1b3-41bb-9dfe-5404b90d52ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]/div/div/h2</value>
      <webElementGuid>9ef55dbb-1ec6-4d4a-affd-f3f9c80c0052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Shop shop for dogs' or . = 'Shop shop for dogs')]</value>
      <webElementGuid>1177b8ce-2441-4c5d-839c-4df7c89f8d89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
