<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dog</name>
   <tag></tag>
   <elementGuidId>08a9d557-225c-42a5-ba91-2d3c19542a1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rcnt']/div[2]/div/div/div[3]/div/div/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.PZPZlf.ssJ7i.B5dxMb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a2e399a3-1820-4137-9302-9f875eb39c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PZPZlf ssJ7i B5dxMb</value>
      <webElementGuid>8b875fe3-99ad-4818-9817-115f30ad65b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e885de08-8109-4b37-b90a-fc5722b7305c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attrid</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>173956b8-7ff0-4102-937b-a87fb41a8888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>6b83336f-8dce-4be5-9137-ae94c2643109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dog</value>
      <webElementGuid>41b71498-4eaa-4506-9533-93933ad1e49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rcnt&quot;)/div[@class=&quot;XqFnDf&quot;]/div[1]/div[@class=&quot;kp-wholepage-osrp&quot;]/div[@class=&quot;HdbW6 MjUjnf VM6qJ&quot;]/div[@class=&quot;hHq9Z&quot;]/div[1]/div[@class=&quot;KsRP6&quot;]/div[@class=&quot;MDY31c&quot;]/div[@class=&quot;QpPSMb&quot;]/div[@class=&quot;DoxwDb&quot;]/div[@class=&quot;PZPZlf ssJ7i B5dxMb&quot;]</value>
      <webElementGuid>161900b2-2dc6-4cba-8557-24d8e59552b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rcnt']/div[2]/div/div/div[3]/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>a8725db8-b20c-4ec8-9fb2-2110c18d6d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>a6bc9722-d53d-428c-9ca5-521094ef1534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Dog' or . = 'Dog')]</value>
      <webElementGuid>b2c0f206-5069-4bc1-bda5-9ec85660ef3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
