<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sounds</name>
   <tag></tag>
   <elementGuidId>55e32516-0a10-4111-afe0-da2a230efbfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='JTPWx']/span[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9902f407-53a6-4abe-b52b-1e5456b2aa6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>REySof</value>
      <webElementGuid>68034a0a-3798-4b45-8f5f-856ddb8025ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sounds</value>
      <webElementGuid>df8cd5e2-56b9-4b27-bfc3-ade58dedd9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JTPWx&quot;)/span[@class=&quot;NQyKp&quot;]/span[@class=&quot;REySof&quot;]</value>
      <webElementGuid>844a8394-affc-4f79-8c68-c51eaf8e897f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='JTPWx']/span[3]/span</value>
      <webElementGuid>3eabd959-132c-4580-aca3-ef42e3b91640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span</value>
      <webElementGuid>9a981a96-ee83-47d8-ac4e-82fe7010da6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sounds' or . = 'Sounds')]</value>
      <webElementGuid>cdfe2d49-86b1-472c-badf-3c7e2178d83c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
