<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_nm8ICe</name>
   <tag></tag>
   <elementGuidId>2420b3a7-0779-432d-869b-f41da7fb37c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//g-scrolling-carousel[@id='_0S5NZaH0Et6pqtsPx7GguA0_12']/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.nm8ICe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>703a126a-774c-4721-a74c-c483f09fd5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>Bz112c</value>
      <webElementGuid>17f40e9f-4132-479b-95f8-02eaa1bd9cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nm8ICe</value>
      <webElementGuid>3b4556cb-8b3a-4a90-9497-830eb23c5bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_0S5NZaH0Et6pqtsPx7GguA0_12&quot;)/div[@class=&quot;acCJ4b&quot;]/div[@class=&quot;EDblX GpHuwc&quot;]/div[@class=&quot;cUYA9&quot;]/div[@class=&quot;m6cn6&quot;]/div[@class=&quot;tkRsEc&quot;]/div[@class=&quot;nm8ICe&quot;]</value>
      <webElementGuid>4c517649-284b-40f9-87fb-1caa2f1ce16e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//g-scrolling-carousel[@id='_0S5NZaH0Et6pqtsPx7GguA0_12']/div/div/div/div/div/div</value>
      <webElementGuid>2c1a5bc7-054b-422f-adfe-e7f29287ca59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//g-scrolling-carousel/div/div/div/div/div/div</value>
      <webElementGuid>5310244a-7ad0-4013-b3fa-2f0febcbc139</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
