<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dog</name>
   <tag></tag>
   <elementGuidId>9e9fe9ef-56a7-45b8-89e1-d473fcd9a43c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//g-scrolling-carousel[@id='_0S5NZaH0Et6pqtsPx7GguA0_12']/div/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.b3CYFf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>629dce1f-9bf9-4f7b-8562-9f8f9138d3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b3CYFf</value>
      <webElementGuid>69746446-2a09-41e4-9b1a-d6b359794913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dog</value>
      <webElementGuid>79bfbd12-9e16-47da-a23c-6d86ed0ddc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_0S5NZaH0Et6pqtsPx7GguA0_12&quot;)/div[@class=&quot;acCJ4b&quot;]/div[@class=&quot;EDblX GpHuwc&quot;]/div[@class=&quot;cUYA9&quot;]/div[@class=&quot;m6cn6&quot;]/div[@class=&quot;b3CYFf&quot;]</value>
      <webElementGuid>d41122d5-cb6b-4609-b12a-0784530f23b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//g-scrolling-carousel[@id='_0S5NZaH0Et6pqtsPx7GguA0_12']/div/div/div/div/div[2]</value>
      <webElementGuid>4cfe73c9-d301-4964-bdaf-ebbd74e33c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//g-scrolling-carousel/div/div/div/div/div[2]</value>
      <webElementGuid>5acb66d5-583c-4cec-af3a-96e812372b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Dog' or . = 'Dog')]</value>
      <webElementGuid>d6bea1e6-a85a-4b34-a864-9db694c2d93b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
