<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Joined DateJob TitleHR ManagerJob Speci_124982</name>
   <tag></tag>
   <elementGuidId>a28701ff-b8ea-4d9f-a1a2-77f3bd8f9db1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div[2]/div/form/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.oxd-grid-3.orangehrm-full-width-grid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8fa6795a-ed78-4fb7-ba16-3612a58fa937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-grid-3 orangehrm-full-width-grid</value>
      <webElementGuid>6b5c7a8d-7641-41a5-9fb3-e88ea2a79063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Joined DateJob TitleHR ManagerJob SpecificationNot DefinedJob CategoryOfficials and ManagersSub UnitHuman ResourcesLocationTexas R&amp;DEmployment StatusFull-Time Permanent</value>
      <webElementGuid>60d5520b-16fe-4eb7-829e-733f7e39a1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-card-container&quot;]/div[@class=&quot;orangehrm-edit-employee&quot;]/div[@class=&quot;orangehrm-edit-employee-content&quot;]/div[@class=&quot;orangehrm-horizontal-padding orangehrm-vertical-padding&quot;]/form[@class=&quot;oxd-form&quot;]/div[@class=&quot;oxd-form-row&quot;]/div[@class=&quot;oxd-grid-3 orangehrm-full-width-grid&quot;]</value>
      <webElementGuid>958351ea-f5d2-405f-a704-a65110485a06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div[2]/div/form/div/div</value>
      <webElementGuid>9e778f37-8c9f-40c8-a7ff-8d0b1b185069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>4062ccda-fa7e-469b-9e04-9aaebb949545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Joined DateJob TitleHR ManagerJob SpecificationNot DefinedJob CategoryOfficials and ManagersSub UnitHuman ResourcesLocationTexas R&amp;DEmployment StatusFull-Time Permanent' or . = 'Joined DateJob TitleHR ManagerJob SpecificationNot DefinedJob CategoryOfficials and ManagersSub UnitHuman ResourcesLocationTexas R&amp;DEmployment StatusFull-Time Permanent')]</value>
      <webElementGuid>567ee9db-5c4d-4b5d-98f4-d479607dec76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
