<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Time at WorkPunched InPunched In Jan 16_94b309</name>
   <tag></tag>
   <elementGuidId>561d131a-537b-454e-b870-035eb96b6953</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.oxd-layout-context</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>44aa6976-f16e-4fa6-ade1-f1124a16368b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-layout-context</value>
      <webElementGuid>79793651-c5ba-4aaa-a549-6c0aa3d47abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Time at WorkPunched InPunched In: Jan 16th at 06:00 AM (GMT 4)9h 51m TodayThis WeekNov 06 - Nov 120h 0m My Actions(1) Pending Self ReviewQuick LaunchAssign LeaveLeave ListTimesheetsApply LeaveMy LeaveMy TimesheetBuzz Latest PostsTest 18  Shaja09-11-2023 09:38 AMTest text 85Test 18  Shaja09-11-2023 08:56 AMTest 18  Shaja09-11-2023 08:49 AMTest text 25Test 18  Shaja09-11-2023 08:45 AMTestingTest 18  Shaja09-11-2023 08:44 AMTestingEmployees on Leave TodayNo Employees are on Leave TodayEmployee Distribution by Sub UnitHuman ResourcesUnassignedEmployee Distribution by LocationTexas R&amp;DUnassigned</value>
      <webElementGuid>96adf2b6-83f7-4b2d-84a4-2eb43f589760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]</value>
      <webElementGuid>004321cd-22bc-436e-925f-912845fc84a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]</value>
      <webElementGuid>7c03280e-63f7-44cd-8d37-ea6d5826bf25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>5c2f575c-cc74-4855-9f78-d5c83852f351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Time at WorkPunched InPunched In: Jan 16th at 06:00 AM (GMT 4)9h 51m TodayThis WeekNov 06 - Nov 120h 0m My Actions(1) Pending Self ReviewQuick LaunchAssign LeaveLeave ListTimesheetsApply LeaveMy LeaveMy TimesheetBuzz Latest PostsTest 18  Shaja09-11-2023 09:38 AMTest text 85Test 18  Shaja09-11-2023 08:56 AMTest 18  Shaja09-11-2023 08:49 AMTest text 25Test 18  Shaja09-11-2023 08:45 AMTestingTest 18  Shaja09-11-2023 08:44 AMTestingEmployees on Leave TodayNo Employees are on Leave TodayEmployee Distribution by Sub UnitHuman ResourcesUnassignedEmployee Distribution by LocationTexas R&amp;DUnassigned' or . = 'Time at WorkPunched InPunched In: Jan 16th at 06:00 AM (GMT 4)9h 51m TodayThis WeekNov 06 - Nov 120h 0m My Actions(1) Pending Self ReviewQuick LaunchAssign LeaveLeave ListTimesheetsApply LeaveMy LeaveMy TimesheetBuzz Latest PostsTest 18  Shaja09-11-2023 09:38 AMTest text 85Test 18  Shaja09-11-2023 08:56 AMTest 18  Shaja09-11-2023 08:49 AMTest text 25Test 18  Shaja09-11-2023 08:45 AMTestingTest 18  Shaja09-11-2023 08:44 AMTestingEmployees on Leave TodayNo Employees are on Leave TodayEmployee Distribution by Sub UnitHuman ResourcesUnassignedEmployee Distribution by LocationTexas R&amp;DUnassigned')]</value>
      <webElementGuid>d5a0e2a6-c587-4396-860c-a423e645102c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
